In [ ]:
import pandas as pd

data={'apples':[3,2,0,1],'orange':[0,3,7,2]}
df=pd.DataFrame(data)
df

s=0

for i in range(4):
  s+=df.loc[i,'apples']

print(s)

6

In [87]:
import pandas as pd

data={'id':[1,2,3,4,5],'name':["sairaj","hemanth","amar","aditya","gokul"],'branch':["cse","cse","cse","cse","cse"],'section':[1,1,2,2,4]}
df=pd.DataFrame(data,index=[450,526,483,669,716])
df
df['namelowe']=df['name'].str.lower()
df['nameupper']=df['branch'].str.upper()
print(df)
# df. to_csv('student.csv')

# df.to_json('student.json')

     id     name branch  section namelowe nameupper
450   1   sairaj    cse        1   sairaj       CSE
526   2  hemanth    cse        1  hemanth       CSE
483   3     amar    cse        2     amar       CSE
669   4   aditya    cse        2   aditya       CSE
716   5    gokul    cse        4    gokul       CSE

In [1]:
import pandas as pd
df=pd.read_csv('tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [2]:
import pandas as pd
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [94]:
movies_df=pd.read_csv("movies.csv",index_col="title")
# movies_df
# movies_df.head()
# movies_df.head(5)
# movies_df.tail(2)
# movies_df.info()
# movies_df.shape
# movies_df.describe()
#4803,23

# x=pd.concat([movies_df,movies_df])
# x.shape

# total_nans=movies_df.isna().sum().sum()
# nans_per_column=movies_df.isna().sum()

# print("Total NaNs: ",total_nans)
# print("NaNs per column: ",nans_per_column)
# movies_df.dropna()
# movies_df.dropna(axis=1)
# movies_df.fillna(0)
movies_df['original']=movies_df['original_title'].str.upper()
print(movies_df)

                                          index     budget  \
title
Avatar                                        0  237000000
Pirates of the Caribbean: At World's End      1  300000000
Spectre                                       2  245000000
The Dark Knight Rises                         3  250000000
John Carter                                   4  260000000
...                                         ...        ...
El Mariachi                                4798     220000
Newlyweds                                  4799       9000
Signed, Sealed, Delivered                  4800          0
Shanghai Calling                           4801          0
My Date with Drew                          4802          0

                                                                            genres  \
title
Avatar                                    Action Adventure Fantasy Science Fiction
Pirates of the Caribbean: At World's End                  Adventure Fantasy Action
Spectre                                                     Action Adventure Crime
The Dark Knight Rises                                  Action Crime Drama Thriller
John Carter                                       Action Adventure Science Fiction
...                                                                            ...
El Mariachi                                                  Action Crime Thriller
Newlyweds                                                           Comedy Romance
Signed, Sealed, Delivered                            Comedy Drama Romance TV Movie
Shanghai Calling                                                               NaN
My Date with Drew                                                      Documentary

                                                                                   homepage  \
title
Avatar                                                          http://www.avatarmovie.com/
Pirates of the Caribbean: At World's End       http://disney.go.com/disneypictures/pirates/
Spectre                                         http://www.sonypictures.com/movies/spectre/
The Dark Knight Rises                                    http://www.thedarkknightrises.com/
John Carter                                            http://movies.disney.com/john-carter
...                                                                                     ...
El Mariachi                                                                             NaN
Newlyweds                                                                               NaN
Signed, Sealed, Delivered                 http://www.hallmarkchannel.com/signedsealeddel...
Shanghai Calling                                                http://shanghaicalling.com/
My Date with Drew                                                                       NaN

                                              id  \
title
Avatar                                     19995
Pirates of the Caribbean: At World's End     285
Spectre                                   206647
The Dark Knight Rises                      49026
John Carter                                49529
...                                          ...
El Mariachi                                 9367
Newlyweds                                  72766
Signed, Sealed, Delivered                 231617
Shanghai Calling                          126186
My Date with Drew                          25975

                                                                                   keywords  \
title
Avatar                                    culture clash future space war space colony so...
Pirates of the Caribbean: At World's End  ocean drug abuse exotic island east india trad...
Spectre                                          spy based on novel secret agent sequel mi6
The Dark Knight Rises                     dc comics crime fighter terrorist secret ident...
John Carter                               based on novel mars medallion space travel pri...
...                                                                                     ...
El Mariachi                               united states\u2013mexico barrier legs arms pa...
Newlyweds                                                                               NaN
Signed, Sealed, Delivered                 date love at first sight narration investigati...
Shanghai Calling                                                                        NaN
My Date with Drew                                      obsession camcorder crush dream girl

                                         original_language  \
title
Avatar                                                  en
Pirates of the Caribbean: At World's End                en
Spectre                                                 en
The Dark Knight Rises                                   en
John Carter                                             en
...                                                    ...
El Mariachi                                             es
Newlyweds                                               en
Signed, Sealed, Delivered                               en
Shanghai Calling                                        en
My Date with Drew                                       en

                                                                    original_title  \
title
Avatar                                                                      Avatar
Pirates of the Caribbean: At World's End  Pirates of the Caribbean: At World's End
Spectre                                                                    Spectre
The Dark Knight Rises                                        The Dark Knight Rises
John Carter                                                            John Carter
...                                                                            ...
El Mariachi                                                            El Mariachi
Newlyweds                                                                Newlyweds
Signed, Sealed, Delivered                                Signed, Sealed, Delivered
Shanghai Calling                                                  Shanghai Calling
My Date with Drew                                                My Date with Drew

                                                                                   overview  \
title
Avatar                                    In the 22nd century, a paraplegic Marine is di...
Pirates of the Caribbean: At World's End  Captain Barbossa, long believed to be dead, ha...
Spectre                                   A cryptic message from Bond’s past sends him o...
The Dark Knight Rises                     Following the death of District Attorney Harve...
John Carter                               John Carter is a war-weary, former military ca...
...                                                                                     ...
El Mariachi                               El Mariachi just wants to play his guitar and ...
Newlyweds                                 A newlywed couple's honeymoon is upended by th...
Signed, Sealed, Delivered                 "Signed, Sealed, Delivered" introduces a dedic...
Shanghai Calling                          When ambitious New York attorney Sam is sent t...
My Date with Drew                         Ever since the second grade when he first saw ...

                                          popularity  ... runtime  \
title                                                 ...
Avatar                                    150.437577  ...   162.0
Pirates of the Caribbean: At World's End  139.082615  ...   169.0
Spectre                                   107.376788  ...   148.0
The Dark Knight Rises                     112.312950  ...   165.0
John Carter                                43.926995  ...   132.0
...                                              ...  ...     ...
El Mariachi                                14.269792  ...    81.0
Newlyweds                                   0.642552  ...    85.0
Signed, Sealed, Delivered                   1.444476  ...   120.0
Shanghai Calling                            0.857008  ...    98.0
My Date with Drew                           1.929883  ...    90.0

                                                                           spoken_languages  \
title
Avatar                                    [{"iso_639_1": "en", "name": "English"}, {"iso...
Pirates of the Caribbean: At World's End           [{"iso_639_1": "en", "name": "English"}]
Spectre                                   [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...
The Dark Knight Rises                              [{"iso_639_1": "en", "name": "English"}]
John Carter                                        [{"iso_639_1": "en", "name": "English"}]
...                                                                                     ...
El Mariachi                                   [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]
Newlyweds                                                                                []
Signed, Sealed, Delivered                          [{"iso_639_1": "en", "name": "English"}]
Shanghai Calling                                   [{"iso_639_1": "en", "name": "English"}]
My Date with Drew                                  [{"iso_639_1": "en", "name": "English"}]

                                            status  \
title
Avatar                                    Released
Pirates of the Caribbean: At World's End  Released
Spectre                                   Released
The Dark Knight Rises                     Released
John Carter                               Released
...                                            ...
El Mariachi                               Released
Newlyweds                                 Released
Signed, Sealed, Delivered                 Released
Shanghai Calling                          Released
My Date with Drew                         Released

                                                                                    tagline  \
title
Avatar                                                          Enter the World of Pandora.
Pirates of the Caribbean: At World's End     At the end of the world, the adventure begins.
Spectre                                                               A Plan No One Escapes
The Dark Knight Rises                                                       The Legend Ends
John Carter                                            Lost in our world, found in another.
...                                                                                     ...
El Mariachi                               He didn't come looking for trouble, but troubl...
Newlyweds                                 A newlywed couple's honeymoon is upended by th...
Signed, Sealed, Delivered                                                               NaN
Shanghai Calling                                                   A New Yorker in Shanghai
My Date with Drew                                                                       NaN

                                          vote_average vote_count  \
title
Avatar                                             7.2      11800
Pirates of the Caribbean: At World's End           6.9       4500
Spectre                                            6.3       4466
The Dark Knight Rises                              7.6       9106
John Carter                                        6.1       2124
...                                                ...        ...
El Mariachi                                        6.6        238
Newlyweds                                          5.9          5
Signed, Sealed, Delivered                          7.0          6
Shanghai Calling                                   5.7          7
My Date with Drew                                  6.3         16

                                                                                       cast  \
title
Avatar                                    Sam Worthington Zoe Saldana Sigourney Weaver S...
Pirates of the Caribbean: At World's End  Johnny Depp Orlando Bloom Keira Knightley Stel...
Spectre                                   Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
The Dark Knight Rises                     Christian Bale Michael Caine Gary Oldman Anne ...
John Carter                               Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                                                     ...
El Mariachi                               Carlos Gallardo Jaime de Hoyos Peter Marquardt...
Newlyweds                                 Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
Signed, Sealed, Delivered                 Eric Mabius Kristin Booth Crystal Lowe Geoff G...
Shanghai Calling                          Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
My Date with Drew                         Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                                                       crew  \
title
Avatar                                    [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...
Pirates of the Caribbean: At World's End  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...
Spectre                                   [{'name': 'Thomas Newman', 'gender': 2, 'depar...
The Dark Knight Rises                     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...
John Carter                               [{'name': 'Andrew Stanton', 'gender': 2, 'depa...
...                                                                                     ...
El Mariachi                               [{'name': 'Robert Rodriguez', 'gender': 0, 'de...
Newlyweds                                 [{'name': 'Edward Burns', 'gender': 2, 'depart...
Signed, Sealed, Delivered                 [{'name': 'Carla Hetland', 'gender': 0, 'depar...
Shanghai Calling                          [{'name': 'Daniel Hsia', 'gender': 2, 'departm...
My Date with Drew                         [{'name': 'Clark Peterson', 'gender': 2, 'depa...

                                                   director  \
title
Avatar                                        James Cameron
Pirates of the Caribbean: At World's End     Gore Verbinski
Spectre                                          Sam Mendes
The Dark Knight Rises                     Christopher Nolan
John Carter                                  Andrew Stanton
...                                                     ...
El Mariachi                                Robert Rodriguez
Newlyweds                                      Edward Burns
Signed, Sealed, Delivered                       Scott Smith
Shanghai Calling                                Daniel Hsia
My Date with Drew                          Brian Herzlinger

                                                                          original
title
Avatar                                                                      AVATAR
Pirates of the Caribbean: At World's End  PIRATES OF THE CARIBBEAN: AT WORLD'S END
Spectre                                                                    SPECTRE
The Dark Knight Rises                                        THE DARK KNIGHT RISES
John Carter                                                            JOHN CARTER
...                                                                            ...
El Mariachi                                                            EL MARIACHI
Newlyweds                                                                NEWLYWEDS
Signed, Sealed, Delivered                                SIGNED, SEALED, DELIVERED
Shanghai Calling                                                  SHANGHAI CALLING
My Date with Drew                                                MY DATE WITH DREW

[4803 rows x 24 columns]

In [29]:
y=x.drop_duplicates()
y.shape

(4803, 23)

In [33]:
t=movies_df.drop_duplicates(inplace=True)

In [37]:
import pandas as pd
ex=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df1=pd.DataFrame(ex,index=['first','second'],columns=['a','b'])
df2=pd.DataFrame(ex,index=['first','second'],columns=['a','b1'])

# print(df1)
# print(df2)
# df1. to_csv('df1.csv')
# df2. to_csv('df2.csv')

        a   b
first   1   2
second  5  10
        a  b1
first   1 NaN
second  5 NaN

In [65]:
import pandas as pd
df={'one':pd.Series([1,2,3],index=['a','b','c']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
# df=pd.DataFrame(d)
# df

# df['three']=pd.Series([10,20,30],index=['a','b','c'])
# df
# df['four']=df['one']+df['three']
# df
# del df['one']
# df
# df=pd.DataFrame(d)
# df[2:4]

   one  two
c  3.0    3
d  NaN    4

In [77]:
import pandas as pd
import numpy as np
df=pd.DataFrame({ 'Age':[25,30,np.nan,40,35],
                  'Deparymnrt':['HR','Finance','Finance',np.nan,'IT']})
print(df)
df['Age'].fillna(df['Age'].mean(),inplace=True)

df['Deparymnrt'].fillna(df['Deparymnrt'].mode()[0],inplace=True)
print(df)

    Age Deparymnrt
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Deparymnrt
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_10011/3994942935.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_10011/3994942935.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Deparymnrt'].fillna(df['Deparymnrt'].mode()[0],inplace=True)

In [78]:
df_ffill=df.copy()
df_ffill.fillna(method='ffill',inplace=True)
print(df_ffill)

    Age Deparymnrt
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_10011/527151055.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill',inplace=True)

In [79]:
df_bfill=df.copy()
df_bfill.fillna(method='bfill',inplace=True)
print(df_bfill)

    Age Deparymnrt
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_10011/2985061711.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill',inplace=True)

In [81]:
import pandas as pd

# Sample dataset with inconsistent date formats
df = pd.DataFrame({
    'Date': ['2025-01-05', '05/01/2025', 'Jan 5, 2025', '2025.01.05']
})

# Convert all dates to standard ISO format (YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

print(df)

         Date
0  2025-01-05
1         NaN
2         NaN
3         NaN

In [82]:
df = pd.DataFrame({
    'Name': ['Alice', 'BOB', 'charlie', 'DAVID']
})

# Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
print(df)

# Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()

print(df)

      Name Name_lower
0    Alice      alice
1      BOB        bob
2  charlie    charlie
3    DAVID      david
      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      BOB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID